Update build-html.yml

diff --git a/.github/workflows/build-html.yml b/.github/workflows/build-html.yml
--- a/.github/workflows/build-html.yml
+++ b/.github/workflows/build-html.yml
@@ -29,13 +29,7 @@ jobs:
             echo " dita --input=$(pwd)/content/en/orange-heart-master.ditamap --format=html5 --verbose --propertyfile=$(pwd)/resources/build.properties -Dargs.input.dir=$(pwd) "
 
             dita --input=$(pwd)/content/en/orange-heart-master.ditamap --format=html5 --verbose --propertyfile=$(pwd)/resources/build.properties -Dargs.input.dir=$(pwd) 2>&1 | tee log.txt
-
-            ERRORS=$(grep -Ei 'Error|ERROR' log.txt)
-            if [ -n "$ERRORS" ]; then
-                echo "Errors detected in DITA OT build log:"
-                echo "$ERRORS"
-                exit 1
-            fi    
+            
             
       - name: Upload log file as an artifact
         uses: actions/upload-artifact@v4
@@ -54,8 +48,14 @@ jobs:
           name: out-html5-archive
           path: out.tar.gz
 
-      - name: List build output
-        run: ls -R out
+      - name: List build output and errors
+        run: |
+          if grep -qEi 'Error|ERROR' log.txt; then
+              echo "Errors detected in DITA OT build log:"
+              grep -Ei 'Error|ERROR' log.txt
+              exit 1
+          fi
+          ls -R out
 
       - name: Delete out folder
         run: |
