Update dita-ot-build-actions.yml

diff --git a/.github/workflows/dita-ot-build-actions.yml b/.github/workflows/dita-ot-build-actions.yml
--- a/.github/workflows/dita-ot-build-actions.yml
+++ b/.github/workflows/dita-ot-build-actions.yml
@@ -30,6 +30,10 @@ jobs:
 
             dita --input=$(pwd)/content/en/orange-heart-master.ditamap --format=html5 --verbose --propertyfile=$(pwd)/resources/build.properties -Dargs.input.dir=$(pwd) 2>&1 | tee log.txt
 
+            if grep -q "Error: [DOT" log.txt; then
+                echo "Error detected in DITA OT build log."
+                exit 1
+            fi
 
       - name: Upload log file as an artifact
         uses: actions/upload-artifact@v4
